### ISSUE TITLE
Show 'size' of an '<array>' as a "slot-reference" syntax

### ISSUE THREAD

**Issue by fraya** [cgay/dylan-koans#1]
https://github.com/cgay/dylan-koans/blob/99053339183487def426631c17e6ae064b2855dd/sources/arrays/arrays.dylan#L21 
shows the size of an `<array>` using the G.F `size`. Additionally it could show that a call to a function that takes one argument and returns one value that represents a property of an object, can also be called using a '.' dot like `chess-board.size`.

To avoid the duplication of the test:

```
assert-equal(TODO, size(chess-board));
assert-equal(TODO, chess-board.size));
```
It can be added with an `assert-equal` already done:

```
assert-equal(TODO, size(chess-board));
assert-equal(size(chess-board), chess-board.size));
```

**Comment by cgay** [comment]
Like this?  https://github.com/cgay/dylan-koans/commit/2f18fda88d1f07da55dc67d38a52f8d67ce4004f
